# Generated by Django 5.1.3 on 2024-11-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
