# Generated by Django 5.1.3 on 2024-12-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_shop_app', '0003_tea'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
